server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: Delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**, 
        - id: inventory
          uri: http://localhost:8083
          predicates:
            - Path=/products/**, 
        - id: Notification
          uri: http://localhost:8084
          predicates:
            - Path=/messages/**, 
        - id: Payment
          uri: http://localhost:8085
          predicates:
            - Path=/payments/**, 
        - id: ViewPage
          uri: http://localhost:8086
          predicates:
            - Path=, /productInfos/**, /orderHistories/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: Delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, 
        - id: inventory
          uri: http://inventory:8080
          predicates:
            - Path=/products/**, 
        - id: Notification
          uri: http://notification:8080
          predicates:
            - Path=/messages/**, 
        - id: Payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: ViewPage
          uri: http://viewPage:8080
          predicates:
            - Path=, /productInfos/**, /orderHistories/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
